### ISSUE TITLE
[Fansly] highest quality no longer being downloaded

### ISSUE THREAD

**Issue by duatharben** [DIGITALCRIMINALS/UltimaScraperAPI#16]
Sometime around April or May, the timeline API no longer provides the highest source quality on the media entity by default. Only the variants contain the highest quality. Sadly, everything that has been syncing for the last several months unfortunately is 720p or so.

I'll open a PR as soon as I can fix, but I believe the best approach is just to always loop the variants and sort by height.

**Comment by duatharben** [comment]
Most timelines I have checked, it seems not affect older posts prior to the chnage, so scraping a fresh timeline today will download source quality for older posts until late April-ish, then switch to 720p

**Comment by DIGITALCRIMINALS** [comment]
Hmm, I am able to download highest resolution content as of August 8th 2023
